# -*- coding: utf-8 -*-
"""미션1_Free_Tempo.ipynb의 사본

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1GtL-Hv3bw5PhaJ2rwDWgkLI0fPj-TqIH

미션 1
"""



num_list=[1,5,7,15,16,22,28,29]

def get_odd_num(num_list):
  list=[]
  for number in num_list:
    if number/2!=int(number/2):
      list.append(number)
  return list

get_odd_num(num_list)

"""미션 2"""

sentence = "way a is there will a is there where"

def reverse_sentence(sentence):
  sentence_list=sentence.split()
  sentence_list.reverse()
  sentence_list[0]=sentence_list[0].capitalize()
  reverse_sentence=' '.join(sentence_list)
  return  reverse_sentence

print(reverse_sentence(sentence))

"""미션 3"""

score=[(100,100), (95,90),(55,60), (75,80),(70,70)]

def get_avg(score):
  for number, personal_score in enumerate(score):
    average=sum(personal_score)/len(personal_score)
    print(f'{number+1} 번, 평균 : {average}')

get_avg(score)

"""미션 4"""

import collections, operator

def reduce(function, iterable, initializer=None):
  it = iter(iterable)
  if initializer is None: 
    value = next(it) 
  else: 
    value = initializer 
  for element in it: 
    value = function(value, element)
  return value

def merge_dict_1(dict_first,dict_second):
  concat_dict=[dict_first,dict_second]
  result = dict(reduce(operator.add,
         map(collections.Counter, concat_dict)))
  return result

dict_first={'사과':30 , '배' : 15, '감':10, '포도':10}
dict_second={'사과':5 , '감' : 25, '배':15, '귤':10}

merge_dict_1(dict_first,dict_second)

"""미션4 다른 풀이"""

def merge_dict_2(dict_first,dict_second):
  merge_dict={}
  index=list(set(dict_first.keys())|set(dict_second.keys()))
  for fruit in index:
    if fruit in dict_first.keys():
      dict_first_value=dict_first[fruit]
    else:
      dict_first_value=0
    if fruit in dict_second.keys():
      dict_second_value=dict_second[fruit]
    else:
      dict_second_value=0
    merge_dict[fruit]=dict_first_value+dict_second_value
  return merge_dict

merge_dict_2(dict_first,dict_second)

"""미션5"""

inputs = "cat32dog16cow5"

import re

def find_string_list(inputs):
  input_number_elimination=re.sub(r"[0-9]"," ",inputs)
  input_number_elimination=input_number_elimination.split(" ")
  input_number_elimination=[v for v in input_number_elimination if v]
  return input_number_elimination

find_string_list(inputs)